version: "3.9"
services:
  allen_nlp:
    build:
      context: "."
      dockerfile: "Dockerfile.allen"
    ports:
      - "5053:5000"
    volumes:
      - ./allen_nlp:/app
    networks:
      - default
  flask:
    build:
      context: "."
      dockerfile: "Dockerfile.flask"
    ports:
      - "5051:5000"
    volumes:
      - ./Flask-docker-example:/app
    networks:
      - default
      - nguml_backend_default
  stanza:
    build:
      context: "."
      dockerfile: "Dockerfile.stanza"
    ports:
      - "5052:5000"
    volumes:
      - ./stanza:/app
    networks:
      - default
networks: 
  default:
    driver: bridge
  nguml_backend_default:
    external: true