FROM openjdk:slim
COPY --from=python:3.8 / /

WORKDIR /app

COPY stanza/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ENV CORENLP_HOME /app/stanza_corenlp
RUN export CORENLP_HOME

#install other things
#for now nothing

COPY stanza/ .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]