version: "3.9"
services:
  allen_nlp:
    build:
      dockerfile: "Dockerfile.allen"
    ports:
      - "5003:5003"
    volumes:
      - ./allen_nlp:/app
    networks:
      - default
  flask:
    build:
      dockerfile: "Dockerfile.flask"
    ports:
      - "5001:5001"
    volumes:
      - ./Flask-docker-example:/app
    networks:
      - default
      - nguml_default
  stanza:
    build:
      dockerfile: "Dockerfile.stanza"
    ports:
      - "5002:5002"
    volumes:
      - ./stanza:/app
    networks:
      - default
networks: 
  default:
    driver: bridge
  nguml_default:
    external: true