version: "3.9"
services:
  allen_nlp:
    build:
      context: "."
    ports:
      - "5053:5000"
    volumes:
      - nlp_data:/opt
    networks:
      - allen_net
volumes:
  nlp_data:
networks:
  allen_net:
    driver: bridge